# Generated by Django 6.1.1 on 2026-09-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('collection_name', models.CharField(default='personal_documents', max_length=100)),
                ('indexed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
